{% set name = "pathogen-profiler" %}
{% set version = "0.1" %}
{% set sha256 = "f985900147e147f827052224dfd67dca4ebaae2bc6a73fa9d89bcca194529762" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/jodyphelan/{{name}}/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  number: 3

requirements:
  host:
    - python
    - pip
  run:
    - python
    - trimmomatic
    - bwa
    - bowtie2
    - minimap2
    - parallel
    - samtools=1.9
    - bcftools=1.9

test:
  imports:
    - pathogenprofiler

about:
  home: https://github.com/jodyphelan/{{ name }}
  license: GPL3
  license_file: LICENSE
  summary: Microbial assembly pipeline for Illumina paired-end reads
